Layers : [0, 1, 2]
T list : [0, 0, 40]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.916126, test avg acc: 0.874622
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.202188, test avg acc: 0.148453


Layers : [0, 1, 2]
T list : [0, 0, 45]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.914506, test avg acc: 0.872541
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.230956, test avg acc: 0.170826


Layers : [0, 1, 2]
T list : [0, 0, 50]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.909643, test avg acc: 0.865965
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.259319, test avg acc: 0.198907


Layers : [0, 1, 2]
T list : [0, 0, 55]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.913290, test avg acc: 0.867378
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.282820, test avg acc: 0.215029


Layers : [0, 1, 2]
T list : [0, 0, 60]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.908023, test avg acc: 0.863174
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.308347, test avg acc: 0.232651


Layers : [0, 1, 2]
T list : [0, 0, 65]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.910454, test avg acc: 0.871297
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.339951, test avg acc: 0.268058


Layers : [0, 1, 2]
T list : [0, 0, 70]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.900729, test avg acc: 0.853593
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.363452, test avg acc: 0.274686


Layers : [0, 1, 2]
T list : [0, 0, 75]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.901540, test avg acc: 0.856256
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.386953, test avg acc: 0.306477


Layers : [0, 1, 2]
T list : [0, 0, 80]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.901945, test avg acc: 0.852924
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.410454, test avg acc: 0.318721


Layers : [0, 1, 2]
T list : [0, 5, 40]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.923015, test avg acc: 0.884331
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.213938, test avg acc: 0.157198


Layers : [0, 1, 2]
T list : [0, 5, 45]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.907618, test avg acc: 0.860674
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.245543, test avg acc: 0.185988


Layers : [0, 1, 2]
T list : [0, 5, 50]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.913290, test avg acc: 0.871791
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.279579, test avg acc: 0.212192


Layers : [0, 1, 2]
T list : [0, 5, 55]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.912075, test avg acc: 0.864291
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.300648, test avg acc: 0.228814


Layers : [0, 1, 2]
T list : [0, 5, 60]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.912885, test avg acc: 0.873919
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.324959, test avg acc: 0.252145


Layers : [0, 1, 2]
T list : [0, 5, 65]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.901540, test avg acc: 0.855797
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.353728, test avg acc: 0.273808


Layers : [0, 1, 2]
T list : [0, 5, 70]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.898298, test avg acc: 0.846547
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.376013, test avg acc: 0.290186


Layers : [0, 1, 2]
T list : [0, 5, 75]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.899514, test avg acc: 0.850471
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.393031, test avg acc: 0.303767


Layers : [0, 1, 2]
T list : [0, 5, 80]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.900324, test avg acc: 0.851965
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.407212, test avg acc: 0.321012


Layers : [0, 1, 2]
T list : [0, 10, 40]
Test pre attack :: test acc: 0.928687, test avg acc: 0.898744
Test pre attack defense :: test acc: 0.916937, test avg acc: 0.875994
Test attack :: test acc: 0.091977, test avg acc: 0.057750
Test defense :: test acc: 0.244733, test avg acc: 0.187866


Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
Traceback (most recent call last):
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 276, in <module>
    test(args, io)
  File "/home/robust/diffusion-point-cloud/test_pgd_attack.py", line 115, in test
    test_loader = DataLoader(ModelNet40Attack(args.num_points),
                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
TypeError: ModelNet40Attack.__init__() missing 1 required positional argument: 'path'
